/**
 * Build-time feature flags.
 *
 * `NEXT_PUBLIC_*` values are inlined by Next.js at build time, so these are
 * plain constants rather than a runtime lookup.
 */

/**
 * The inbox-scan tab does not connect to Gmail or Naver Mail. It renders
 * receipts generated by `getSimulatedInboxReceipts` to demonstrate how the
 * active-subscription filter works, and registering its results writes sample
 * data into the user's real subscription list.
 *
 * It therefore stays hidden unless explicitly enabled for a demo. Turn it on
 * with `NEXT_PUBLIC_SHOW_INBOX_PREVIEW=true`. Once a real mail integration
 * exists, drop this flag along with the simulation.
 */
export const SHOW_INBOX_PREVIEW = process.env.NEXT_PUBLIC_SHOW_INBOX_PREVIEW === "true";
